baseurl = "http://lazbog.pro/"
relativeURLs = false
languageCode = "ru-Ru"
title = "Personal blog for LazBog"
disqusShortname = "lazbog"
paginate = 5
publishDir = "docs"

[taxonomies]
	tag = "tags"
	tutorial = "tutorials"

[params]
	showglobe = true

	favicon = "favicon.ico"
	
	analytics = "code-here"

	github = "https://github.com/lazbog"
	twitter = "https://twitter.com/lazbog"
	email = "lazbog@tuta.io"
	googleplus = "https://plus.google.com/106815883580854777966"
	
	profilepic = "img/profile.png"
	
	title = "LazBog"
	subtitle = "MY PERSONAL BLOG"
	
	[[params.navlinks]]
	name = "About"
	url = "about/"
	
	[[params.navlinks]]
	name = "Blog"
	url = ""
	
	[[params.navlinks]]
	name = "Tutorials"
	url = "tutorial/"
