baseurl = "http://lazbog.pro/"
relativeURLs = false
languageCode = "ru-Ru"
title = "LazBog - мой личный блог"
description = "Содержимое головы человека по имени Богданъ"
disqusShortname = "lazbog"
paginate = 5
publishDir = "docs"

[taxonomies]
	tag = "tags"
	tutorial = "tutorials"

[params]
	showglobe = true

	favicon = "favicon.ico"
	
	analytics = "code-here"

	vkontakte = "https://vk.com/lazbog"
	facebook = "https://fb.com/lazbog"
	github = "https://github.com/lazbog"
	twitter = "https://twitter.com/lazbog"
	email = "lazbog@tuta.io"
	googleplus = "https://plus.google.com/106815883580854777966"
	
	profilepic = "img/profile.png"
	
	title = "LazBog"
	subtitle = "My own blog"
	
	[[params.navlinks]]
	name = "About me"
	url = "about/"
	
	[[params.navlinks]]
	name = "Blog"
	url = ""
	
	[[params.navlinks]]
	name = "Tutorial"
	url = "tutorial/"
